export const LOADING_STARTED ="ACCOUNT_LOADING_STARTED";
export const LOADING_FAILED = "ACCOUNT_LOADING_FAILED";


export const LOAD_ADDRESSES = "LOAD_ADDRESSES";
export const SET_ADDRESS_ACTIVE = "SET_ADDRESS_ACTIVE";
export const EDIT_ADDRESS = "EDIT_ADDRESS";
export const DELETE_ADDRESS  = "DELETE_ADDRESS";
export const INIT_ADDRESS_EDITOR = "INIT_ADDRESS_EDITOR";
export const SET_EDITOR_ERRORS = "SET_EDITOR_ERRORS";

export const LOAD_ORDERS = "LOAD_ORDERS";
export const LOAD_SINGLE_ORDER  = "LOAD_SINGLE_ORDER";
export const REODER_SINGLE_ORDER  = "REODER_SINGLE_ORDER";

export const LOAD_DOWNLOADS = "LOAD_DOWNLOADS";
export const LOAD_REWARDS = "LOAD_REWARDS";
export const LOAD_TRANSACTIONS = "LOAD_TRANSACTIONS";

export const LOAD_RETURNS = "LOAD_RETURNS";
export const LOAD_RETURNS_NEXT_PAGE = "LOAD_RETURNS_NEXT_PAGE";
export const LOAD_RETURNED_ORDER_DETAILS = "LOAD_RETURNED_ORDER_DETAILS";

export const LOAD_ADD_RETURN_PAGE = "LOAD_ADD_RETURN_PAGE";
export const LOAD_ADD_RETURN_ERRORS = "LOAD_ADD_RETURN_ERRORS";

export const LOAD_ACCOUNT_EDIT_PAGE = "LOAD_ACCOUNT_EDIT_PAGE";
export const LOAD_CHANGE_PASSWORD_PAGE = "LOAD_CHANGE_PASSWORD_PAGE";
