export const START_LOADING = "CHECKOUT_START_LOADING";
export const END_LOADING = "CHECKOUT_END_LOADING";

export const LOAD_ADDRESSES_LIST = "LOAD_ADDRESSES_LIST";
export const SET_DEFAULT_ADDRESS_ID = "SET_DEFAULT_ADDRESS_ID";

export const SET_PAYMNET_ADDRESS_ID  = "SET_PAYMNET_ADDRESS_ID";
export const SET_SHIPPING_ADDRESS_ID = "SET_SHIPPING_ADDRESS_ID";

export const LOAD_PAYMENT_METHODS_LIST = "LOAD_PAYMENT_METHODS_LIST";
export const SET_PAYMENT_METHOD = "SET_PAYMENT_METHOD";

export const LOAD_SHIPPING_METHODS_LIST = "LOAD_SHIPPING_METHODS_LIST";
export const SET_SHIPPING_METHOD = "SET_SHIPPING_METHOD";

export const SET_CHECKOUT_TRANSLATIONS = "SET_CHECKOUT_TRANSLATIONS";
export const SET_GUEST_CHECKOUT_DATA = "SET_GUEST_CHECKOUT_DATA";
export const SET_AGREE_DATA = "SET_AGREE_DATA";
