export const LOADING_STARTED = 'PRODUCT_LOADING_STARTED';
export const LOADING_FAILED = 'PRODUCT_LOADING_FAILED';

export const FETCH_PROUDCT = 'FETSH_PROUDCT';
export const FETCH_REVIEWS = 'FETCH_REVIEWS';

export const ADD_OPTION_VALUE = 'ADD_OPTION_VALUE';
export const ADD_GROUP_OF_OPTION_VALUE = 'ADD_GROUP_OF_OPTION_VALUE';
export const REMOVE_OPTION_VALUE = 'REMOVE_OPTION_VALUE';
