export const LOADING_STARTED ="SEARCH_LOADING_STARTED";
export const LOADING_FAILED = "SEARCH_LOADING_FAILED";

export const FETCH_SERACH_QUERY = "FETCH_SERACH_QUERY";
export const FETCH_SEARCH_QUERY_BY_FILTER = "FETCH_SEARCH_QUERY_BY_FILTER";
export const ADD_NEXT_SEARCH_PAGE = "ADD_NEXT_SEARCH_PAGE";
export const CHANGE_SEARCH_KEYWORD = "CHANGE_SEARCH_KEYWORD";
export const CLEAR_SEARCH = "CLEAR_SEARCH";