export const LOAD_HOMELAYOUT = "LOAD_HOMELAYOUT";
export const LOAD_TRNASLATION_STRINGS = "LOAD_TRNASLATION_STRINGS";
export const LOAD_APP_SETTINGS = "LOAD_APP_SETTINGS";
export const APP_LOADED = "APP_LOADED";
export const LOAD_COUNTRIES = "LOAD_COUNTRIES";
export const LOAD_ZONES = "LOAD_ZONES";
export const SET_CONTACT_INFO = "SET_CONTACT_INFO";