export const LOADING_STARTED ="SHOP_LOADING_STARTED";
export const LOADING_FAILED = "SHOP_LOADING_FAILED";


export const FETCH_SPECIALS_PAGE = "FETCH_SPECIALS_PAGE";

export const MANUFACTURERS_LIST_LOADED = "MANUFACTURERS_PAGE_LOADED";
export const SINGLE_MANUFACTURERE_LOADED = "SINGLE_MANUFACTURERE_LOADED";
export const LOAD_MANUFACTURER_NEXT_PAGE = "LOAD_MANUFACTURER_NEXT_PAGE";

export const CATEGORIES_LIST_LOADED = "CATEGORIES_LIST_LOADED";
export const SINGLE_CATEOGORY_LOADED = "SINGLE_CATEOGORY_LOADED";
export const LOAD_CATEOGRY_NEXT_PAGE = "LOAD_CATEOGRY_NEXT_PAGE";

export const WISHLIST_LOADED = "WISHLIST_LOADED";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const CART_LOADED = "CART_LOADED";
export const INCREASE_CART = "INCREASE_CART";
export const DECREASE_CART = "DECREASE_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const COMPARE_PAGE_LOADED = "COMPARE_PAGE_LOADED";


export const SET_SEPCIAL_PRODUCT_PAGE_PATH = "SET_SEPCIAL_PRODUCT_PAGE_PATH";
export const LOAD_SEPCIAL_PRODUCT_PAGE = "LOAD_SEPCIAL_PRODUCT_PAGE";
export const LOAD_NEXT_SEPCIAL_PRODUCT_PAGE = "LOAD_NEXT_SEPCIAL_PRODUCT_PAGE";
export const FETCH_MORE_BOTTOM_LOADING = "fetch_more_bottom_loading";
export const STOP_FETCH_MORE_BOTTOM_LOADING = "stop_fetch_more_bottom_loading";




